language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ivat/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ivat/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-017520537469"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "AKIAQIFCOF56YM6GJU7J"
  secret_access_key: "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"
